services:
  app:
    depends_on:
      - db
    build:
      context: .
    image: subscription-tracker
    ports:
      - '3000:3000'
      - '5555:5555'
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
